call plug#begin('~/.vim/plugged')
	Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
   	Plug 'junegunn/fzf.vim'
    	Plug 'OmniSharp/omnisharp-vim'
    	Plug 'maralla/completor.vim'
	Plug 'quramy/tsuquyomi'
    	Plug 'leafgarland/typescript-vim'
    	Plug 'groenewege/vim-less'
    	Plug 'w0rp/ale'
call plug#end()

let g:typescript_compiler_binary = 'tsc'
let g:typescript_compiler_options = ''
let g:tsuquyomi_completion_detail = 1
let g:tsuquyomi_search_term_min_length = 3
let g:typescript_indent_disable = 1
let g:ale_completion_enabled = 1
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
let g:ale_open_list = 1
let g:ale_completion_enabled = 1
let g:ale_echo_cursor = 0
let g:netrw_liststyle = 1
let g:netrw_banner = 0

let g:OmniSharp_selector_ui = 'fzf'
let g:ale_linters = {
\ 'cs': ['OmniSharp']
\}

let mapleader=","

set laststatus=2
set ffs=unix,dos
set ff=unix
set number
set noswapfile
set spell spelllang=en_us
set completeopt=longest,menuone
set shiftwidth=2 noexpandtab
set tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab
set spell spelllang=en_us
set wildignore+=*/node_modules/*
set wildignore+=*/target/*
set wildignore+=*/dist/*
set wildmode=longest,list

highlight Pmenu ctermbg=Gray ctermfg=Black
highlight PmenuSel ctermbg=Black ctermfg=White

syntax on
