case $- in        
    *i*) ;;        
      *) return;;        
esac        
         
HISTCONTROL=ignoreboth        
         
shopt -s histappend    
    
HISTSIZE=1000    
HISTFILESIZE=2000    
         
shopt -s checkwinsize        
        
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"    

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
export PS1="\[\e[32;1m\]\u@\[\e[38;1m\]ide \[\e[30;1m\]\W> \[\e[0m\]"

export TERM=xterm

#DOTNET
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_ROOT="/home/default/Applications/dotnet"
export PATH="/home/default/Applications/dotnet:$PATH"

#NODE
export PATH="/home/default/Applications/node/bin:$PATH"

#GOLANG
export GOROOT="/home/default/Applications/go"
export PATH="/home/default/Applications/go/bin:$PATH"
export GOPATH="/home/default/.go-packages"
export PATH="/home/default/.go-packages/bin:$PATH"

#RUST
export PATH="/home/default/.cargo/bin:$PATH"
export CARGO_HOME="/home/default/.cargo"
export RUST_SRC_PATH="/home/default/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
